<?php

$this->pageTitle = 'Change Password';

$this->asset()->append(array(
    '/vox/js/form/validator.js',
));

$passwordExpired = false;

if ($this->currentUser->isPasswordExpired()) {
    $passwordExpired = true;
    $this->form->actions->removeElement('cancelBtn');
}

?>
<div id="change-password-page">
    <? if ($passwordExpired): ?>
        <div class="notice">
            Your password is currently expired. You must change it to continue.
        </div>
    <? endif; ?>

    <p>Please complete the following form to change your password.</p>
    <?= $this->form ?>
</div>
<script type="text/javascript" charset="utf-8">

$(function () {
    $('#details-password').focus();

    $('#submitBtn').button({ icons: { primary: 'ui-icon-key' }});
    $('#form-link-cancelBtn').button({ icons: { primary: 'ui-icon-close' }});
    
    $('#changepassword').validator({
        showMessages: true,
        validators: {
            '#details-newPassword': [
                ['mustMatch', {
                    match: '#details-password',
                    message: 'Password must be different',
                    inverse: true
                }],
                
                <? if ($this->minLength): ?>
                
                ['stringLength', {
                    min: <?= $this->minLength ?>,
                    message: 'Passwords must contain at least <?= $this->minLength ?> characters',
                    breakOnFail: false
                }],
                
                <? endif; ?>
                
                ['mustMatch', {
                    match: '#details-newPasswordVerify',
                    message: 'Passwords must match',
                    breakOnFail: false
                }]
            ],
            '#details-newPasswordVerify': [
                ['mustMatch', {
                    match: '#details-newPassword',
                    message: 'Passwords must match'
                }]
            ]
        }
    });
});

</script>